CREATE TABLE tableName (
    c1  VARCHAR NOT NULL,
    c2  INT NOT NULL,
    c3  SMALLINT NOT NULL,
    c4  SMALLINT NOT NULL,
    c5  INT NOT NULL,
    c6  BIGINT NOT NULL,
    c7  SMALLINT NOT NULL,
    c8  INT NOT NULL,
    c9  BIGINT NOT NULL,
    c10 VARCHAR NOT NULL,
    c11 DOUBLE PRECISION NOT NULL,
    c12 DOUBLE PRECISION NOT NULL,
    c13 VARCHAR NOT NULL,
    c14 INT NOT NULL
);